language: node_js
node_js:
  - 12

install: npm ci

script:
  - BUILD_TIME=$(TZ=":Europe/Kiev" date '+%Y-%m-%d %H:%M:%S %z') npm run build

after_success:
  - curl --request GET "https://api.telegram.org/bot$BOT_TOKEN/sendMessage?chat_id=$CHAT_ID&text=Build=$TRAVIS_BUILD_NUMBER/Succeeded"

after_failure:
  - curl --request GET "https://api.telegram.org/bot$BOT_TOKEN/sendMessage?chat_id=$CHAT_ID&text=Build=$TRAVIS_BUILD_NUMBER/Failed"

cache:
  npm: true

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: ./dist
    fqdn: pay.lovilave.com.ua
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: ./dist
    fqdn: pay.test.l-l.cloud
    target_branch: master
    repo: lovelave/pay.test.l-l.cloud
