language: node_js
node_js:
  - 12

install: npm ci

script:
  - BUILD_TIME=$(TZ=":Europe/Kiev" date '+%Y-%m-%d %H:%M:%S %z') npm run build

cache:
  npm: true

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
    local_dir: ./dist
    fqdn: pay.lovilave.com.ua
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
    target_branch: master
    repo: lovelave/pay.test.l-l.cloud
    local_dir: ./dist
    fqdn: pay.test.l-l.cloud
