language: node_js
node_js:
  - 12

install: npm ci

script:
  - BUILD_TIME=$(date)
  - npm run build

cache:
  npm: true

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: ./dist
  fqdn: pay.lovilave.com.ua
