language: node_js
node_js:
  - 12

install: npm ci

script:
  - BUILD_TIME=$(TZ=":Europe/Kiev" date '+%Y-%m-%d %H:%M:%S %z') npm run build

env:
  - NODE_ENV=production URL=https://pay.lovilave.com.ua
  - NODE_ENV=test URL=https://pay.test.l-l.cloud

before_deploy:
  - if [ "$NODE_ENV" = 'test' ]; then cp ./robots/robots.txt ./dist/robots.txt; fi;

after_success:
  - curl --request GET "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage?chat_id=${CHAT_ID}&text=Quickpay%20LL%0ABuild%20%23${TRAVIS_BUILD_NUMBER}.%20Succeeded%0ACommit:%20%22${TRAVIS_COMMIT_MESSAGE}%22%0ANODE_ENV%20=%20${NODE_ENV}%0A${URL}"

after_failure:
  - curl --request GET "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage?chat_id=${CHAT_ID}&text=Quickpay%20LL%0ABuild%20%23${TRAVIS_BUILD_NUMBER}.%20Failed%0ACommit:%20%22${TRAVIS_COMMIT_MESSAGE}%22%0ANODE_ENV%20=%20${NODE_ENV}"

cache:
  npm: true

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
      condition: $NODE_ENV = production
    local_dir: ./dist
    fqdn: $URL
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
      condition: $NODE_ENV = test
    local_dir: ./dist
    fqdn: $URL
    target_branch: master
    repo: lovelave/pay.test.l-l.cloud
