language: node_js
node_js:
  - 12

install: npm ci

script:
  - BUILD_TIME=$(TZ=":Europe/Kiev" date '+%Y-%m-%d %H:%M:%S %z') npm run build

after_success:
  - curl --request GET "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage?chat_id=${CHAT_ID}&text=Quickpay%20LL%0ABuild%20${TRAVIS_BUILD_NUMBER}%20Succeeded%0ACommit:%20%22${TRAVIS_COMMIT}%22"

after_failure:
  - curl --request GET "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage?chat_id=${CHAT_ID}&text=Quickpay%20LL%0ABuild%20${TRAVIS_BUILD_NUMBER}%20Failed%0ACommit:%20%22${TRAVIS_COMMIT}%22"

cache:
  npm: true

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: ./dist
    fqdn: pay.lovilave.com.ua
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: ./dist
    fqdn: pay.test.l-l.cloud
    target_branch: master
    repo: lovelave/pay.test.l-l.cloud
