language: node_js
node_js:
  - 12

install: npm ci

script:
  - BUILD_TIME=$(TZ=":Europe/Kiev" date '+%Y-%m-%d %H:%M:%S %z') npm run build

env:
  - NODE_ENV=production
  - NODE_ENV=test

before_deploy:
  - cp ./robots/robots.txt ./dist/robots.txt

after_success:
  - curl --request GET "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage?chat_id=${CHAT_ID}&text=Quickpay%20LL%0ABuild%20%23${TRAVIS_BUILD_NUMBER}.%%3Cstrong%3ESucceeded%3C%2Fstrong%3E%0ACommit:%20%22${TRAVIS_COMMIT_MESSAGE}%22%0A%3Ca%20href%3D%22https%3A%2F%2Fpay.lovilave.com.ua%2F%22%3EQuickpay%20LL%3C%2Fa%3E"

after_failure:
  - curl --request GET "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage?chat_id=${CHAT_ID}&text=Quickpay%20LL%0ABuild%20%23${TRAVIS_BUILD_NUMBER}.%20%3Cstrong%3EFailed%3C%2Fstrong%3E%0ACommit:%20%22${TRAVIS_COMMIT_MESSAGE}%22"

cache:
  npm: true

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: ./dist
    fqdn: pay.lovilave.com.ua
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: ./dist
    fqdn: pay.test.l-l.cloud
    target_branch: master
    repo: lovelave/pay.test.l-l.cloud
