language: node_js
node_js: node

install: npm install

script:
  - npm run build

before_deploy:
  - echo "node_modules" > .gitignore

cache:
  npm: true

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: ./dist
