language: node_js
node_js:
  - 12

install: npm ci

script:
  - BUILD_TIME=$(TZ=":Europe/Kiev" date '+%Y-%m-%d %H:%M:%S %z') npm run build

before_deploy:
  - if [ "$NODE_ENV" = test ]; then cp ./robots/robots.txt ./robots.txt; fi;

cache:
  npm: true

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: ./dist
    fqdn: pay.lovilave.com.ua
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
      condition: $NODE_ENV = test
    local_dir: ./dist
    fqdn: pay.test.l-l.cloud
    target_branch: master
    repo: lovelave/pay.test.l-l.cloud
